version: 2.1

parameters:
  cron:
    type: boolean
    default: false

workflows:
  monthly-release:
    when: << pipeline.parameters.cron >>
    # Publishes the `YYYY.MM` tag as well as the `current` tag
    jobs:
      - schedule-fix:
          filters:
            branches:
              ignore: /.*/
      - test:
          requires:
            - schedule-fix
          filters:
            branches:
              ignore: /.*/
          context: cimg-publishing
      - publish-monthly:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
          context: cimg-publishing
  main:
    when:
      not: << pipeline.parameters.cron >>
    # Always runs. When the main branch runs, publishes the `edge` Docker tag
    jobs:
      - test:
          context: cimg-publishing
      - publish-edge:
          requires:
            - test
          filters:
            branches:
              only: main
          context: cimg-publishing
  manual-monthly:
    when:
      not: << pipeline.parameters.cron >>
    # Used to respin this month's snapshot
    jobs:
      - test:
          filters:
            tags:
              only: /^monthly$/
            branches:
              ignore: /.*/
          context: cimg-publishing
      - publish-monthly:
          requires:
            - test
          filters:
            tags:
              only: /^monthly$/
            branches:
              ignore: /.*/
          context: cimg-publishing

jobs:
  test:
    docker:
      # references for this digest refers to cimg/base:2022.01
      - image: cimg/base@sha256:bf1a115683b4b0366dce294accf87ba967b9ad0d78f29d974b71dc7e79ffbee2
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          name: "Build Dockerfiles"
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker pull -a fagiani/cimg-base
            ./build-images.sh
            echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
      - run:
          name: "Publish Docker Hub Description (main branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              # Update the Docker Hub description
              SONAR_VER=0.15.0
              SONAR_URL="https://github.com/felicianotech/sonar/releases/download/v${SONAR_VER}/sonar-v${SONAR_VER}-linux-amd64.tar.gz"
              mkdir -p $HOME/bin
              curl -sSL $SONAR_URL | tar -xz -C $HOME/bin sonar

              sonar set description fagiani/cimg-base ./README.md
            fi

  publish-edge:
    docker:
      - image: cimg/base@sha256:bf1a115683b4b0366dce294accf87ba967b9ad0d78f29d974b71dc7e79ffbee2
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          name: "Build & Tag Images"
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker pull -a fagiani/cimg-base
            ./build-images.sh
      - deploy:
          name: "Publish Docker Images (main branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              # Copy multiarch images with new tags
              REGCLIENT_VER=0.4.4
              REGCLIENT_URL="https://github.com/regclient/regclient/releases/download/v${REGCLIENT_VER}/regctl-linux-amd64"
	      curl -L $REGCLIENT_URL > $HOME/bin/regctl
	      chmod 755 $HOME/bin/regctl
              
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:edge-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:edge-20.04
              regctl image copy fagiani/cimg-base:22.04 fagiani/cimg-base:edge-22.04
              regctl image copy fagiani/cimg-base:22.04 fagiani/cimg-base:edge
            fi

  publish-monthly:
    docker:
      - image: cimg/base@sha256:bf1a115683b4b0366dce294accf87ba967b9ad0d78f29d974b71dc7e79ffbee2
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          name: "Build & Tag Images"
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker pull -a fagiani/cimg-base
            ./build-images.sh
      - deploy:
          name: "Publish Docker Images (main branch only)"
          command: |
            REGCLIENT_VER=0.4.4
            REGCLIENT_URL="https://github.com/regclient/regclient/releases/download/v${REGCLIENT_VER}/regctl-linux-amd64"
            curl -L $REGCLIENT_URL > $HOME/bin/regctl
            chmod 755 $HOME/bin/regctl
            VERSION=$( date +%Y.%m )
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:current
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:current-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:current-20.04
              regctl image copy fagiani/cimg-base:22.04 fagiani/cimg-base:current-22.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:stable
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:stable-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:stable-20.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:${VERSION}
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:${VERSION}-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:${VERSION}-20.04
            elif [ "${CIRCLE_TAG}" == "monthly" ]; then
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:current
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:current-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:current-20.04
              regctl image copy fagiani/cimg-base:22.04 fagiani/cimg-base:current-22.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:stable
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:stable-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:stable-20.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:${VERSION}
              regctl image copy fagiani/cimg-base:18.04 fagiani/cimg-base:${VERSION}-18.04
              regctl image copy fagiani/cimg-base:20.04 fagiani/cimg-base:${VERSION}-20.04
              regctl image copy fagiani/cimg-base:22.04 fagiani/cimg-base:${VERSION}-22.04
            fi
  schedule-fix:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Only run on the first Monday of the month"
          command: |
            dom=$(date "+%-d")
            if (( $dom > 7 )); then
              echo "It's not the first week. Skipping."
              exit 1
            fi
